# -*- coding: utf-8 -*-
"""BookStoredataScrap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13fcsGqUJG_jfAHuXZehEq2fLL8gc9IUx
"""

import requests
import bs4 
import pandas as pd

pages=[]
prices=[]
ratings=[]   #empty list
title=[]
urls=[]

page_no = 30 #number of page i

for page in range(1, page_no+1):
  url = ('http://books.toscrape.com/catalogue/page-{}.html'.format(page))
                                                                                          # number of page read 

  pages.append(url)

pages

for item in pages:
  
  pages = requests.get(item)                                                             #read every page

  page_read = bs4.BeautifulSoup(pages.text, 'html.parser')

page_read

for t in page_read('h3'):
  titlee = t.getText()                                                                   #get all title
  title.append(titlee)

for p in page_read('p', class_='price_color'):
  price = p.getText()                                                                    # get all price
  prices.append(price)

prices

for s in page_read.find_all('p', class_= 'star-rating'):
  for k, v in s.attrs.items():
    star = v[1]
                                                                                         # find all books rating
    ratings.append(star)
    print(star)

divs=page_read.find_all('div',class_='image_container')
for thumbs in divs:
    tagss=thumbs.find('img',class_='thumbnail')
    links='http://books.toscrape.com/' + str(tagss['src'])
    newlinks=links.replace('..','')                                                      #find all images
    urls.append(newlinks)

urls

"""### **Data Processing**"""

web_data = {'Title':title,'Price':prices,'Ratings':ratings,'URL':urls}               # create a dictionary

print(len(title))
print(len(prices))                                                                   # see the size of data    
print(len(ratings))
print(len(urls))

df = pd.DataFrame(web_data)                                                         #creating dataframe

df

df.index+=1
df

df['Price']=df['Price'].str.replace('Â£','')

df

df.sort_values(by='Price',ascending=False, inplace = True)

df

df['Ratings']=df['Ratings'].replace({'Three':3,'One':1,'Two':2,'Four':4,'Five':5})

df

df.dtypes

df['Price']=df['Price'].astype(float)

df.corr()

import matplotlib.pyplot as plt
import seaborn as sns


plt.figure(figsize=(5,5))
sns.heatmap(df.corr())